before_script:
  - cd mwa
  
stages:
  - build
  - test
  - deploy
  
.job_template: &azure_upload_file
  stage: deploy
  image: microsoft/azure-cli
  variables: 
    AZURE_STORAGE_ACCOUNT: rimotedeployment
  script:
      - az login --service-principal -u https://deployment.rimote.net -p /keys/azure.pem --tenant $AZURE_TENANT
      - az storage blob upload -f $AZURE_INPUT_FILE -n $AZURE_OUTPUT_FILE -c downloads

.job_template: &go_test
  stage: test
  image: golang:1.11
  script:
      - go test -v ./...
  
.job_template: &go_build  # Hidden key that defines an anchor named 'job_definition'
  stage: build
  image: golang:1.11
  script:
      - echo $LDFLAGS
      - go build
  artifacts:
      paths:
        - ${OUTPUT}

build-linux-arm:
  <<: *go_build
  variables:
    LDFLAGS: "-s -w -X main.GitCommit=${CI_COMMIT_SHA} -X main.Version=${CI_COMMIT_TAG}"
    GOOS: linux
    GOARCH: arm
    GOARM: 7
    OUTPUT: mwa/mwa
    
build-linux-amd64:
  <<: *go_build
  variables:
    LDFLAGS: "-X main.GitCommit=${CI_COMMIT_SHA} -X main.Version=${CI_COMMIT_TAG}"
    GOOS: linux
    GOARCH: amd64
    OUTPUT: mwa/mwa
    
build-win-amd64:
  <<: *go_build
  variables:
    LDFLAGS: "-X main.GitCommit=${CI_COMMIT_SHA} -X main.Version=${CI_COMMIT_TAG}"
    GOOS: windows
    GOARCH: amd64
    OUTPUT: mwa/mwa.exe
    
test-linux-amd64:
  <<: *go_test
  variables:
    GOOS: linux
    GOARCH: amd64
    
deploy-linux-arm:
  dependencies:
    - build-linux-arm
  <<: *azure_upload_file
  variables: 
    AZURE_INPUT_FILE: mwa
    AZURE_OUTPUT_FILE: Wireless-Agent\mwa-${CI_COMMIT_TAG}-arm
    
deploy-linux-amd64:
  dependencies:
    - build-linux-amd64
  <<: *azure_upload_file
  variables: 
    AZURE_INPUT_FILE: mwa
    AZURE_OUTPUT_FILE: Wireless-Agent\mwa-${CI_COMMIT_TAG}-amd64
    
deploy-win-amd64:
  dependencies:
    - build-win-amd64
  <<: *azure_upload_file
  variables: 
    AZURE_INPUT_FILE: mwa.exe
    AZURE_OUTPUT_FILE: Wireless-Agent\mwa-${CI_COMMIT_TAG}-win-x64.exe