before_script:
  - ls mwa
  
cache:
  key: modules
  paths:
    - $HOME/go/pkg/mod

stages:
  - build
  - test
  
.job_template: &go_build_linux  # Hidden key that defines an anchor named 'job_definition'
  stage: build
  image: golang:1.11
  script:
      - echo $FLAGS
      - go build mwa/
      - ls -l $GOPATH/pkg/mod
  artifacts:
      paths:
        - mwa/mwa

linux-arm:
  <<: *go_build_linux
  variables:
    LDFLAGS: "-X main.GitCommit=${CI_COMMIT_SHA} -X main.Version=${CI_COMMIT_TAG}"
    GOOS: linux
    GOARCH: arm
    GOARM: 7
    
linux-amd64:
  <<: *go_build_linux
  variables:
    LDFLAGS: "-X main.GitCommit=${CI_COMMIT_SHA} -X main.Version=${CI_COMMIT_TAG}"
    GOOS: linux
    GOARCH: amd64
    
test-linux-amd64:
  stage: test
  script:
      - go test -v ./...
    