before_script:
  - cd mwa
  
cache:
  key: modules
  paths:
    - $HOME/go/pkg/mod

stages:
  - build
  - test

.job_template: &go_test
  stage: test
  image: golang:1.11
  script:
      - go test -v ./...
  
.job_template: &go_build  # Hidden key that defines an anchor named 'job_definition'
  stage: build
  image: golang:1.11
  script:
      - echo $LDFLAGS
      - go build
      - ls -l $GOPATH/pkg/mod
  artifacts:
      paths:
        - ${OUTPUT}

build-linux-arm:
  <<: *go_build
  variables:
    LDFLAGS: "-s -w -X main.GitCommit=${CI_COMMIT_SHA} -X main.Version=${CI_COMMIT_TAG}"
    GOOS: linux
    GOARCH: arm
    GOARM: 7
    OUTPUT: mwa/mwa
    
build-linux-amd64:
  <<: *go_build
  variables:
    LDFLAGS: "-X main.GitCommit=${CI_COMMIT_SHA} -X main.Version=${CI_COMMIT_TAG}"
    GOOS: linux
    GOARCH: amd64
    OUTPUT: mwa/mwa
    
build-win-amd64:
  <<: *go_build
  variables:
    LDFLAGS: "-X main.GitCommit=${CI_COMMIT_SHA} -X main.Version=${CI_COMMIT_TAG}"
    GOOS: windows
    GOARCH: amd64
    OUTPUT: mwa/mwa.exe
    
test-linux-amd64:
  <<: *go_test
  variables:
    GOOS: linux
    GOARCH: amd64
  
    