before_script:
  - cd mwa
  
.job_template: &go_build  # Hidden key that defines an anchor named 'job_definition'
  stage: build
  image: golang:latest
  script:
      - ls -l
      - cd mwa
      - go build -ldflags "-X main.GitCommit=${GIT_COMMIT} -X main.Version=${GIT_TAG}"

linux-arm:
  <<: *go_build
  variables:
    GOOS: linux
    GOARCH: arm
    GOARM: 7

linux-amd64:
  <<: *go_build
  variables:
    GOOS: linux
    GOARCH: amd64

stages:
    - build

compile:
    stage: build
    script:
      - ./build.sh
    artifacts:
      paths:
        - mwa
