before_script:
  - cd mwa
  
cache:
  paths:
    - $HOME/go/pkg/mod
  
.job_template: &go_build_linux  # Hidden key that defines an anchor named 'job_definition'
  image: golang:1.11
  script:
      - go build -ldflags "-X main.GitCommit=${GIT_COMMIT} -X main.Version=${GIT_TAG}"
      - ls -l $GOPATH/pkg/mod
  artifacts:
      paths:
        - mwa/mwa

linux-arm:
  <<: *go_build_linux
  variables:
    GOOS: linux
    GOARCH: arm
    GOARM: 7

linux-amd64:
  <<: *go_build_linux
  variables:
    GOOS: linux
    GOARCH: amd64

    
