language: go
go:
- '1.11' 
jobs:
    include:
        - stage: build-unittest-win-amd64
          env: GIMME_OS=windows GIMME_ARCH=amd64
          script: 
            - cd mwa
            - /bin/bash ../build.sh
        - stage: build-unittest-linux-amd64
          env: GIMME_OS=linux GIMME_ARCH=amd64
          script: 
            - cd mwa
            - /bin/bash ../build.sh
        - stage: build-release-github-linux-arm
          env: GIMME_OS=linux GIMME_ARCH=arm GIMME_GOARM=7
          script: 
            - cd mwa
            - /bin/bash ../build.sh
          deploy:
            provider: releases
            api_key:
                secure: Izy+TpMZVaCo6CRh89w0TTwPbEq6hMQ91EVrBBvKkRlhzdk9rR+Bd6+Wzxw6fDNqk0eDEVsBxDLLfr5tMBf8oLKQnvJ+0X4XMUs+C8Tt5MBH3RrHczvSu77Dwb1EHQCY7rjmxdDljDYrofyr9n8qoXZOBsn/NvK+8sapnwkydEqj25h8IGr9q3qJ2Q+6KcbNLu4IwNJxfQuJ4P4TZihbBSQrg3lO2ncwWCtFa7PsGmpLh5P/rDk0Axw9uk/q7oJPcVT9hwE5eQIw1d7QprR3gOvpfx8l5Yefqqp8Jc7UaRTAmQ5kArwctVlkfxyT8c90ZZhsQ9H5DNSMo0uD7u8E/b/p0na9ngS6IaV1QjH8TQmCzxWowfvU7UkAxWtCs5HMDb/Y5TQtNJrIGAhgK2bMgkxT+SZKvehOYJRaPE8vtkXhslQ/6b5SxFtKAiE2SecgFJ/+D1a+q//nj3I1D3rEBibE6fc0YYiPt5oCD09OIwr2KiBg6n+RwRSBYViEewzjV3VZVmHf7gCXksXxUPcdP2zqJF8quT7heS0D0Uzj4yuOAkUISuyFv5Bure+FcclAIF+xZVK/IhpDLV4KdPM5XcHuXzW50hCBRrFVYtOuYXc+HMlxUUynvzkjnrhl3XElMGxpE7ddkJRoeo5htwvazuzCaqBHLkOy/s6YGQZZcTM=
            file: mwa
            skip_cleanup: true